# CI/CD Pipeline for the leapflow.
# This is just a bare minimum action written.
# Actions added are: Installing node, yarn, and golang. Lint and building files. Simple echo script for deploy.

name: build and test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubunutu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Frontend
        working-directory: app
        run: |
          yarn install
          yarn build
          
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      
      - name: Lint Go
        run: go fmt ./server
        
      - name: Build Go
        run: go build -o server ./server