name: BUILD AND TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Frontend
        working-directory: app
        run: |
          yarn install
          yarn test
          yarn build

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build Go
        working-directory: server
        run: go build -o server ./...
